#!/bin/bash

echo "================================================"
echo "🔧 一键修复所有 PocketBase 集合"
echo "================================================"
echo ""

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${YELLOW}📋 需要创建的集合：${NC}"
echo "1. tournaments (赛事)"
echo "2. topics (辩题)"
echo "3. timer_projects (计时器)"
echo "4. users 字段更新"
echo ""

echo -e "${RED}⚠️  重要步骤：${NC}"
echo ""
echo "请在 PocketBase Admin 中手动创建以下集合："
echo ""
echo "================================================"
echo "🏆 Collection 1: tournaments"
echo "================================================"
echo "1. 打开: http://127.0.0.1:8090/_/"
echo "2. 点击 'New collection'"
echo "3. Name: tournaments"
echo "4. Type: Base collection"
echo "5. 添加字段 (点击 + New field):"
echo ""
echo "   name             Text     (Required)"
echo "   title            Text"
echo "   description      Text"
echo "   startDate        Text"
echo "   endDate          Text"
echo "   registrationDeadline  Text"
echo "   date             Text"
echo "   location         Text"
echo "   type             Text"
echo "   status           Text"
echo "   price            Number"
echo "   teamsize         Text"
echo "   organizer        Text"
echo "   contact          Text"
echo "   category         Text"
echo "   image            Text"
echo "   totalTeams       Number"
echo "   playersPerTeam   Number"
echo "   participationRequirements  Text"
echo "   registrationLink Text"
echo "   ruleBookLink     Text"
echo "   award            Text"
echo ""
echo "6. 进入 API Rules 标签"
echo "   List/Search rule: 留空（公开访问）"
echo "   View rule: 留空（公开访问）"
echo "   Create rule: @request.auth.id != \"\""
echo "   Update rule: @request.auth.id != \"\""
echo "   Delete rule: @request.auth.id != \"\""
echo ""
echo "7. 保存集合"
echo ""
echo "================================================"
echo "📝 Collection 2: topics"
echo "================================================"
echo "1. 点击 'New collection'"
echo "2. Name: topics"
echo "3. Type: Base collection"
echo "4. 添加字段:"
echo ""
echo "   text             Text     (Required)"
echo "   explanation      Text"
echo "   area             Text"
echo "   language         Text"
echo "   tournament       Text"
echo "   ratings          JSON"
echo "   averageRating    Number"
echo ""
echo "5. API Rules: 同上"
echo "6. 保存集合"
echo ""
echo "================================================"
echo "⏱️  Collection 3: timer_projects"
echo "================================================"
echo "1. 点击 'New collection'"
echo "2. Name: timer_projects"
echo "3. Type: Base collection"
echo "4. 添加字段:"
echo ""
echo "   name             Text     (Required)"
echo "   description      Text"
echo "   type             Text     (Required)"
echo "   duration         Number"
echo "   createdBy        Text     (Required)"
echo ""
echo "5. API Rules: 同上"
echo "6. 保存集合"
echo ""
echo "================================================"
echo "👤 Collection 4: users 字段"
echo "================================================"
echo "1. 点击 users 集合"
echo "2. 点击 Fields 标签"
echo "3. 添加字段:"
echo ""
echo "   wechatOpenid     Text     (✅ Unique)"
echo "   wechatUnionid    Text"
echo "   avatar           URL"
echo ""
echo "4. 保存"
echo ""
echo "================================================"
echo ""
echo -e "${GREEN}✅ 完成以上步骤后：${NC}"
echo ""
echo "1. 刷新浏览器页面"
echo "2. 重新尝试注册"
echo "3. 所有功能应该正常工作"
echo ""
echo "================================================"
echo ""
echo -e "${YELLOW}💡 提示：如果觉得手动创建太麻烦，我可以生成导入脚本${NC}"
echo ""

